import 'package:flutter/material.dart';
import 'package:kb_mobile_app/models/form_section.dart';
import 'package:kb_mobile_app/models/input_field.dart';

// single, group house =< caregiver
class OvcServicesChildCasePlanGap {
  static List<FormSection> getFormSections({
    required String firstDate,
  }) {
    //Date for HIVS&D to be completed
    return [
      FormSection(
          name: 'DOMAIN HEALTH',
          translatedName: 'BOPHELO BO BOTLE',
          id: 'Health',
          color: const Color(0xFF4D9E49),
          borderColor: const Color(0xFF4D9E49),
          inputFields: [
            InputField(
                id: 'cx4xBY4jZXM',
                name: 'HIV S&D',
                translatedName: 'Tšebeletso ea HIV S&D',
                valueType: 'TRUE_ONLY',
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'SIEeRmPm0Q0',
                allowFuturePeriod: true,
                name: '(HIV S&D) Projected date for completion',
                translatedName: 'Letsatsi la HIV S&D le tla phetheloa',
                valueType: 'DATE',
                firstDate: firstDate,
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),

                InputField(
                    id: 'ztDAwmkSwKf',
                    name: 'Provide Oral Health Hygiene Messaging',
                    translatedName: 'Tšebeletso a HTS ',
                    valueType: 'TRUE_ONLY',
                    isReadOnly: true,
                    inputColor: const Color(0xFF4D9E49),
                    labelColor: const Color(0xFF737373)),
                InputField(
                    id: 'bK18Ebt1cRa',
                    allowFuturePeriod: true,
                    name: 'Date for Hygiene Messaging to be completed',
                    translatedName: 'Letsatsi la HTS le tla phetheloa',
                    valueType: 'DATE',
                    firstDate: firstDate,
                    inputColor: const Color(0xFF4D9E49),
                    labelColor: const Color(0xFF737373)),
                InputField(
                    id: 'vqRohVpTK2G',
                    name: 'ART literacy',
                    translatedName: 'Tšebeletso a HTS ',
                    valueType: 'TRUE_ONLY',
                    isReadOnly: true,
                    inputColor: const Color(0xFF4D9E49),
                    labelColor: const Color(0xFF737373)),
                InputField(
                    id: 'vUMhUm3i0b0',
                    allowFuturePeriod: true,
                    name: 'Date for ART literacy to be completed',
                    translatedName: 'Letsatsi la HTS le tla phetheloa',
                    valueType: 'DATE',
                    firstDate: firstDate,
                    inputColor: const Color(0xFF4D9E49),
                    labelColor: const Color(0xFF737373)),
            InputField(
                id: 'HKCv7lkLexo',
                name: 'HIV ADHERANCE SUPPORT',
                translatedName: 'Tšebeletso ea HIV ADHERANCE SUPPORT',
                valueType: 'TRUE_ONLY',
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'd3X7sRgkQkl',
                name: '(HIV ADHERANCE SUPPORT) Name of responsible internal person',
                translatedName: 'Motho ea ikarabellang ka hare ho HIV ADHERANCE SUPPORT ',
                valueType: 'TEXT',
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'd8vFkGjiux4',
                name: '(HIV ADHERANCE SUPPORT ) Name of responsible external Person',
                translatedName: 'Motho ea ikarabellang ka ntle ho HIV ADHERANCE SUPPORT ',
                valueType: 'TEXT',
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'JzlLk2tW4xh',
                allowFuturePeriod: true,
                name: '( HIV ADHERANCE SUPPORT ) Projected date for completion',
                translatedName: 'Letsatsi la HIV ADHERANCE SUPPORT le tla phetheloa',
                valueType: 'DATE',
                firstDate: firstDate,
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'XoSPWmpWXCy',
                name: 'HTS',
                translatedName: 'Tšebeletso a HTS ',
                valueType: 'TRUE_ONLY',
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'iFv7FJeG3V1',
                allowFuturePeriod: true,
                name: '(HTS) Projected date for completion',
                translatedName: 'Letsatsi la HTS le tla phetheloa',
                valueType: 'DATE',
                firstDate: firstDate,
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'ylSjcj6cv42',
                name: 'HIVTREAT',
                translatedName: 'Tšebeletso a HIVTREAT',
                valueType: 'TRUE_ONLY',
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'elqeNdaYNTS',
                name: '(HIVTREAT) Name of responsible internal person',
                translatedName: 'Motho ea ikarabellang ka hare ho HIVTREAT',
                valueType: 'TEXT',
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'IhzyIy3tzo0',
                name: '(HIVTREAT) Name of responsible external Person',
                translatedName: 'Motho ea ikarabellang ka ntle ho HIVTREAT',
                valueType: 'TEXT',
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'qMrZcC7VvCV',
                allowFuturePeriod: true,
                name: '(HIVTREAT) Projected date for completion',
                translatedName: 'Letsatsi la TBTREAT le tla phetheloa',
                valueType: 'DATE',
                firstDate: firstDate,
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
                InputField(
                    id: 'bRv4ZZy5MDH',
                    name: 'TBTREAT',
                    translatedName: 'Tšebeletso a TBTREAT',
                    valueType: 'TRUE_ONLY',
                    inputColor: const Color(0xFF4D9E49),
                    labelColor: const Color(0xFF737373)),
                InputField(
                    id: 'Wc58mUb3AXg',
                    name: '(TBTREAT) Name of responsible internal person',
                    translatedName: 'Motho ea ikarabellang ka hare ho TBTREAT',
                    valueType: 'TEXT',
                    inputColor: const Color(0xFF4D9E49),
                    labelColor: const Color(0xFF737373)),
                InputField(
                    id: 'OPmcOXe5Ogy',
                    name: '(TBTREAT) Name of responsible external Person',
                    translatedName: 'Motho ea ikarabellang ka ntle ho TBTREAT',
                    valueType: 'TEXT',
                    inputColor: const Color(0xFF4D9E49),
                    labelColor: const Color(0xFF737373)),
                InputField(
                    id: 'mvDI6Jr40kI',
                    allowFuturePeriod: true,
                    name: '(TBTREAT) Projected date for completion',
                    translatedName: 'Letsatsi la TBTREAT le tla phetheloa',
                    valueType: 'DATE',
                    firstDate: firstDate,
                    inputColor: const Color(0xFF4D9E49),
                    labelColor: const Color(0xFF737373)),
            InputField(
                id: 'dTFLFtUUeEK',
                name: 'SAIDS',
                translatedName: 'Tšebeletso a SAIDS',
                valueType: 'TRUE_ONLY',
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'emAJOTWYHVq',
                name: '(SAIDS) Name of responsible internal person',
                translatedName: 'Motho ea ikarabellang ka hare ho SAIDS',
                valueType: 'TEXT',
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'lwa1qFrFISz',
                name: '(SAIDS) Name of responsible external Person',
                translatedName: 'Motho ea ikarabellang ka ntle ho SAIDS',
                valueType: 'TEXT',
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'jlu7TDN7khJ',
                allowFuturePeriod: true,
                name: '(SAIDS) Projected date for completion',
                translatedName: 'Letsatsi la SAIDS le tla phetheloa',
                valueType: 'DATE',
                firstDate: firstDate,
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'x4yAqv4z2Xv',
                name: 'IMMUNIZATION',
                translatedName: 'Tšebeletso a IMMUNIZATION',
                valueType: 'TRUE_ONLY',
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'tYYpfnshIvw',
                name: '(IMMUNIZATION) Name of responsible internal person',
                translatedName: 'Motho ea ikarabellang ka hare ho IMMUNIZATION',
                valueType: 'TEXT',
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'bn0EIFjqXes',
                name: '(IMMUNIZATION) Name of responsible external Person',
                translatedName: 'Motho ea ikarabellang ka ntle ho IMMUNIZATION',
                valueType: 'TEXT',
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'eTDE6zroxBC',
                allowFuturePeriod: true,
                name: '(IMMUNIZATION) Projected date for completion',
                translatedName: 'Letsatsi la IMMUNIZATION le tla phetheloa',
                valueType: 'DATE',
                firstDate: firstDate,
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'uvJV4WGc5ct',
                name: 'FOOD SUPPLIMENTS',
                translatedName: 'Tšebeletso ea FOOD SUPPLIMENTS',
                valueType: 'TRUE_ONLY',
                isReadOnly: true,
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'F2IOqOr4EuV',
                allowFuturePeriod: true,
                name: '(FOOD SUPPLIMENTS) Projected date for completion',
                translatedName: 'Letsatsi la FOOD SUPPLIMENTS le tla phetheloa',
                valueType: 'DATE',
                firstDate: firstDate,
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'EaJTFrklMo5',
                name: 'FOOD SUPPORT',
                translatedName: 'Tšebeletso ea  FOOD SUPPORT',
                valueType: 'TRUE_ONLY',
                isReadOnly: true,
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'WAq2HJHXZYS',
                allowFuturePeriod: true,
                isReadOnly: true,
                name: '(FOOD SUPPORT) Projected date for completion',
                translatedName: 'Letsatsi la FOOD SUPPORT le tla phetheloa',
                valueType: 'DATE',
                firstDate: firstDate,
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
                InputField(
                    id: 'CaAOIbC10yv',
                    name: 'Nutrition Messaging',
                    translatedName: 'Tšebeletso ea  Nutrition Messaging ',
                    valueType: 'TRUE_ONLY',
                    inputColor: const Color(0xFF4D9E49),
                    labelColor: const Color(0xFF737373)),
                InputField(
                    id: 'v7GBKBoqJPr',
                    allowFuturePeriod: true,
                    name: '(Nutrition Messaging) Projected date for completion',
                    translatedName: 'Letsatsi la Nutrition Messaging le tla phetheloa',
                    valueType: 'DATE',
                    firstDate: firstDate,
                    inputColor: const Color(0xFF4D9E49),
                    labelColor: const Color(0xFF737373)),
            InputField(
                id: 'AxtahhoHcXV',
                name: 'ANY HEALTH RELATED',
                translatedName: 'Tšebeletso ea  ANY HEALTH RELATED',
                valueType: 'TRUE_ONLY',
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'G6GkSeccLmB',
                name: '(ANY HEALTH RELATED) Name of responsible internal person',
                translatedName: 'Motho ea ikarabellang ka hare ho ANY HEALTH RELATED',
                valueType: 'TEXT',
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'GULhHDCXRvz',
                name: '(ANY HEALTH RELATED) Name of responsible external person',
                translatedName: 'Motho ea ikarabellang ka ntle ho ANY HEALTH RELATED',
                valueType: 'TEXT',
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'ugZKkd3UMNF',
                allowFuturePeriod: true,
                name: '(ANY HEALTH RELATED) Projected date for completion',
                translatedName: 'Letsatsi la ANY HEALTH RELATED le tla phetheloa',
                valueType: 'DATE',
                firstDate: firstDate,
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
          ]),


    ];
  }
}
